//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlexSBProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAME
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Console { get; set; }
        public string Genre { get; set; }
        public bool Complete { get; set; }
        public Nullable<System.DateTime> DateOfCompletion { get; set; }
    }
}
